<?php
return [
    'value' => 'значение',
    'append' => 'присоединять',
    'previous' => 'предыдущий',
    'return' => 'возвращать',
    'input' => 'ввод',
    'key' => 'ключ',
    'overwrite' => 'перезаписать, затереть',
    'contain ' => 'содержит',
    'increment' => 'приращение',
    'decrement' => 'уменьшение',
    'output' => 'вывод',
    'union' => 'объединение',
    'combine' => 'комбинировать',
    'preserve' => 'сохранять',
    'implicit' => 'неявный',
    'dependence' => 'зависимость',
    'dependency' => 'зависимость',
    'behaviour' => 'поведение',
    'event' => 'событие',
    'solution' => 'решение',
    'difference' => 'разница',
    'dimension' => 'измерение',
    'modify' => 'изменять, модифицировать',
    'approach' => 'подход',
    'reserve' => 'резерв',
    'item' => 'пункт',
    'expression' => 'выражение',
    'require' => 'требовать',
    'replace' => 'заменять',
];
