<?php
return [
    'dashboard'=>'приборная панель',
    'sales'=>'продажи',
    'orders'=>'заказы',
    'invoices'=>'счета-фактуры',
    'checks'=>'чеки',
    'shipments'=>'отправки',
    'transactions'=>'операции',
    'billing'=>'выручка',
    'agreements'=>'соглашения',
    'terms'=>'сроки',
    'conditions'=>'условия',
    'gift'=>'подарок',
    'wrapping'=>'упаковка',
    'relations'=>'связи',
    'reviews'=>'отзывы',
    'ratings'=>'рейтинги',
    'testmonials'=>'отзывы',
    'invitations'=>'приглашения',
    'promotions'=>'акции',
    'newsletter'=>'рассылка',
    'survey'=>'опрос',
    'notifications'=>'уведомления',
    'currency'=>'валюта',
    'permissions'=>'разрешения',
    'delivery'=>'доставка',
    'shipping'=>'перевозка',
    'advanced' => 'расширенный',
    'purchase' => 'покупка',
    'inventory' => 'инвентарь',
    'wishlist' => 'лист желаний',
    'persistent' => 'стойкий',
    'payment' => 'оплата',
    'extension' => 'расширение',
    'improved' => 'улучшенный',
    'checkout' => 'проверка',
];
